#!/bin/bash

actualizar_script(){
archivo_local="InformacionGeneral" # Nombre del archivo local
ruta_repositorio="https://github.com/sukigsx/MegaTools_gui.git" #ruta del repositorio para actualizar y clonar con git clone

# Obtener la ruta del script
descarga=$(dirname "$(readlink -f "$0")")
#descarga="/home/$(whoami)/scripts"
git clone $ruta_repositorio /tmp/comprobar >/dev/null 2>&1

diff $descarga/$archivo_local /tmp/comprobar/$archivo_local >/dev/null 2>&1


if [ $? = 0 ]
then
    #esta actualizado, solo lo comprueba
    #echo ""
    #echo -e "${verde} El script${borra_colores} $0 ${verde}esta actualizado.${borra_colores}"
    #echo ""
    var_actualizado="SI"
    chmod -R +w /tmp/comprobar
    rm -R /tmp/comprobar
else
    #hay que actualizar, comprueba y actualiza
    #echo ""
    zenity --warning --title="Megatools - ( Diseñado por SIKIGSX )" --text="Se va a proceder a la actualizacion del componente $0 de forma automatica.\nCargar de nuevo Informacion general." --width=650
    mv /tmp/comprobar/$archivo_local $descarga
    chmod -R +w /tmp/comprobar
    rm -R /tmp/comprobar
    #echo ""
    #echo -e "${verde} El script se ha actualizado.${borra_colores}"
    #sleep 2
    exit
fi
}

actualizar_script

echo -e "Informacion del sistema de $(whoami):\n" >> /tmp/InformacionGeneral; neofetch --off | sed -r "s/\x1B\[[0-9;]*[JKmsu]//g" | sed '1,2d' | head -n -6 >> /tmp/InformacionGeneral; echo -e "\nFin de la informacion" >> /tmp/InformacionGeneral
zenity --text-info --filename=/tmp/InformacionGeneral --title="Informacion general - MegaTools" \
--auto-scroll \
--width=650 \
--height=650 \
--cancel-label="Salir sin preguntar" \
--ok-label="Atras"


if [ $? = "1" ]; then

    # Leer el PID del archivo para matar el script pricipal
    uno_pid=$(</tmp/ProcesoPidDeMegatools)

    # Matar el proceso de uno.sh
    kill $uno_pid
    rm /tmp/InformacionGeneral
    rm /tmp/ProcesoPidDeMegatools
    exit
fi
rm /tmp/InformacionGeneral
rm /tmp/ProcesoPidDeMegatools
