#!/bin/bash

actualizar_script(){
archivo_local="InfoMemoriaRam" # Nombre del archivo local
ruta_repositorio="https://github.com/sukigsx/MegaTools_gui.git" #ruta del repositorio para actualizar y clonar con git clone

# Obtener la ruta del script
descarga=$(dirname "$(readlink -f "$0")")
#descarga="/home/$(whoami)/scripts"
git clone $ruta_repositorio /tmp/comprobar >/dev/null 2>&1

diff $descarga/$archivo_local /tmp/comprobar/$archivo_local >/dev/null 2>&1


if [ $? = 0 ]
then
    #esta actualizado, solo lo comprueba
    echo ""
    #echo -e "${verde} El script${borra_colores} $0 ${verde}esta actualizado.${borra_colores}"
    #echo ""
    var_actualizado="SI"
    chmod -R +w /tmp/comprobar
    rm -R /tmp/comprobar
else
    #hay que actualizar, comprueba y actualiza
    #echo ""
    zenity --warning --title="Megatools - ( Diseñado por SIKIGSX )" --text="Se va a proceder a la actualizacion del componente $0 de forma automatica.."
    mv /tmp/comprobar/$archivo_local $descarga
    chmod -R +w /tmp/comprobar
    rm -R /tmp/comprobar
    #echo ""
    #echo -e "${verde} El script se ha actualizado.${borra_colores}"
    #sleep 2
    exit
fi
}

actualizar_script

# Ejecutar el comando df -h y guardar la salida en una variable
echo -e "Comando: free -h\n" > /tmp/memoria; free -h >> /tmp/memoria; echo -e "\nFinalizada la informacion.\n" >> /tmp/memoria

# Mostrar la salida en una ventana con Zenity
zenity --text-info --filename=/tmp/memoria --title="Informacion de memoria ram - MegaTools" --ok-label="Atras" --cancel-label="Salir sin preguntar" --font="DejaVu Sans Mono" --width=800 --height=450

if [ $? = "1" ]; then
    # Leer el PID del archivo para matar el script pricipal
    uno_pid=$(</tmp/ProcesoPidDeMegatools)
    # Matar el proceso de uno.sh
    kill $uno_pid
    rm /tmp/ProcesoPidDeMegatools
    rm /tmp/memoria
    exit
else
    rm /tmp/ProcesoPidDeMegatools
    rm /tmp/memoria
    exit
fi
