#!/bin/bash

actualizar_script(){
archivo_local="InstalacionDeSoftware" # Nombre del archivo local
ruta_repositorio="https://github.com/sukigsx/MegaTools_gui.git" #ruta del repositorio para actualizar y clonar con git clone

# Obtener la ruta del script
descarga=$(dirname "$(readlink -f "$0")")
#descarga="/home/$(whoami)/scripts"
git clone $ruta_repositorio /tmp/comprobar >/dev/null 2>&1

diff $descarga/$archivo_local /tmp/comprobar/$archivo_local >/dev/null 2>&1


if [ $? = 0 ]
then
    #esta actualizado, solo lo comprueba
    #echo ""
    #echo -e "${verde} El script${borra_colores} $0 ${verde}esta actualizado.${borra_colores}"
    #echo ""
    var_actualizado="SI"
    chmod -R +w /tmp/comprobar
    rm -R /tmp/comprobar
else
    #hay que actualizar, comprueba y actualiza
    #echo ""
    zenity --warning --title="Megatools - ( Diseñado por SIKIGSX )" --text="Se va a proceder a la actualizacion del componente $0 de forma automatica.\nCarga de nuevo $0." --width=650
    mv /tmp/comprobar/$archivo_local $descarga
    chmod -R +w /tmp/comprobar
    rm -R /tmp/comprobar
    #echo ""
    #echo -e "${verde} El script se ha actualizado.${borra_colores}"
    #sleep 2
    exit
fi
}

actualizar_script

#empieza lo gordo
while :
do
# Mostrar un cuadro de diálogo con las opciones
opciones=$(zenity --list --checklist --title="Selecciona las acciones a realizar" --column="Seleccionar" --column="Acción" --column="Descripcion" \
    FALSE "NAVEGADORES" "Si seleccionas esta, instalara todos los navegadores" \
    FALSE "AUDIO - VIDEO" "" \
    FALSE "ENTORNOS GRAFICOS LINUX" "" \
    FALSE "UTILIDADES" "" \
    FALSE "OFIMATICA" "" \
    FALSE "SERVIDORES" "" \
    FALSE "GESTOR DE PAQUETES" "" \
    FALSE "PARA TU TERMINAL" "" \
    FALSE "DISCOS" "" \
    FALSE "JUEGOS" "" \
    FALSE "SEGURIDAD" "" \
    FALSE "MENSAJERIA" "" \
    FALSE "Actualizar paquetes (sudo apt update)" "" \
    FALSE "Actualizar e instalar paquetes (sudo apt upgrade)" "" \
    FALSE "Mostrar uso de memoria (free)" "" \
    --width=850 \
    --height=650 \
    --ok-label="Aceptar" \
    --cancel-label="Atras" \
    --extra-button="Ayuda instalacion software" \
    --extra-button="Salir in confirmar" \
    --separator="|")

#Verificar si se seleccionaron acciones
if [ $? -eq 0 ]; then
    zenity --error --title="MegaTools ( Diseñado por SUKIGSX )" --text="No has seleccionado ninguna opcion del menu." --width=300
else
    zenity --question --title="MegaTools ( Diseñado por SUKIGSX )" --text="¿ Estás seguro de que deseas salir ?" --cancel-label="No" --ok-label="Si" --width=300
    if [ $? -eq 0 ]; then
        exit 0
    fi
fi



# Recorrer las acciones seleccionadas y ejecutar los comandos correspondientes
IFS="|"
read -ra seleccionados <<< "$opciones"
    for opcion in "${seleccionados[@]}"; do
        case "$opcion" in
            "Actualizar paquetes (sudo apt update)")
                sudo apt update;;
            "Actualizar e instalar paquetes (sudo apt upgrade)")
                sudo apt upgrade;;
            "Mostrar uso de memoria (free)")
                free;;
            "Salir in confirmar")
                # Leer el PID del archivo para matar el script pricipal
                uno_pid=$(</tmp/ProcesoPidDeMegatools)

                # Matar el proceso de uno.sh
                kill $uno_pid
                exit
                ;;
            "Ayuda instalacion software")
                zenity --text-info --title="Ayuda - MegaTools" --filename=AyudaInstalacionSoftware --font="DejaVu Sans Mono" --width=650 --height=650
                ;;
        esac
    done
done
