#!/bin/bash

actualizar_script(){
archivo_local="InstalacionDeSoftware" # Nombre del archivo local
ruta_repositorio="https://github.com/sukigsx/MegaTools_gui.git" #ruta del repositorio para actualizar y clonar con git clone

# Obtener la ruta del script
descarga=$(dirname "$(readlink -f "$0")")
#descarga="/home/$(whoami)/scripts"
git clone $ruta_repositorio /tmp/comprobar >/dev/null 2>&1

diff $descarga/$archivo_local /tmp/comprobar/$archivo_local >/dev/null 2>&1


if [ $? = 0 ]
then
    #esta actualizado, solo lo comprueba
    #echo ""
    #echo -e "${verde} El script${borra_colores} $0 ${verde}esta actualizado.${borra_colores}"
    #echo ""
    var_actualizado="SI"
    chmod -R +w /tmp/comprobar
    rm -R /tmp/comprobar
else
    #hay que actualizar, comprueba y actualiza
    #echo ""
    zenity --warning --title="Megatools - ( Diseñado por SIKIGSX )" --text="Se va a proceder a la actualizacion del componente $0 de forma automatica.\nCarga de nuevo $0." --width=650
    mv /tmp/comprobar/$archivo_local $descarga
    chmod -R +w /tmp/comprobar
    rm -R /tmp/comprobar
    #echo ""
    #echo -e "${verde} El script se ha actualizado.${borra_colores}"
    #sleep 2
    exit
fi
}

#actualizar_script

#empieza lo gordo


# Mostrar un cuadro de diálogo con las opciones
opciones=$(zenity --list --checklist --title="Selecciona las acciones a realizar" --column="Seleccionar" --column="Acción" --column="Descripcion" \
    FALSE "NAVEGADORES" "Si seleccionas esta, instalara todos los navegadores" \
    FALSE "AUDIO - VIDEO" "" \
    FALSE "ENTORNOS GRAFICOS LINUX" "" \
    FALSE "UTILIDADES" "" \
    FALSE "OFIMATICA" "" \
    FALSE "SERVIDORES" "" \
    FALSE "GESTOR DE PAQUETES" "" \
    FALSE "PARA TU TERMINAL" "" \
    FALSE "DISCOS" "" \
    FALSE "JUEGOS" "" \
    FALSE "SEGURIDAD" "" \
    FALSE "MENSAJERIA" "" \
    FALSE "Actualizar paquetes (sudo apt update)" "" \
    FALSE "Actualizar e instalar paquetes (sudo apt upgrade)" "" \
    FALSE "Mostrar uso de memoria (free)" "" \
    --width=850 \
    --height=650 \
    --ok-label="Aceptar" \
    --cancel-label="Atras" \
    --extra-button="Ayuda instalacion software" \
    --extra-button="Salir in confitmar" \
    --separator="|")





# Recorrer las acciones seleccionadas y ejecutar los comandos correspondientes
IFS="|"
read -ra seleccionados <<< "$opciones"
for opcion in "${seleccionados[@]}"; do
    case "$opcion" in
        "UTILIDADES")
            echo "utilidades"; read p
            ;;
        "Actualizar e instalar paquetes (sudo apt upgrade)")
            sudo apt upgrade;;
        "Mostrar uso de memoria (free)")
            free;;
        "Salir in confitmar")
            echo "uuuuuuuuuuuuuuuuuuuuuuuuuuu"; read p
            ;;
        "Ayuda instalacion software")
            zenity --text-info --title="Ayuda - MegaTools" --filename=AyudaInstalacionSoftware --font="DejaVu Sans Mono" --width=650 --height=650
            ;;
        "1")
            echo "es 1"; read p
            ;;
        "2")
            echo "es 2"; read p
            ;;
        *)
            echo "no has puesto nada"
            ;;
    esac
done

#Verificar si se seleccionaron acciones
if [ $? = 1 ]; then
    zenity --question --title="MegaTools ( Diseñado por SUKIGSX )" --text="saliendo" --cancel-label="No" --ok-label="Si" --width=300
fi

if [ $? = 0 ]; then
    zenity --question --title="MegaTools ( Diseñado por SUKIGSX )" --text="saliendosssssssssssssssssss" --cancel-label="No" --ok-label="Si" --width=300
fi
