#!/bin/bash

actualizar_script(){
archivo_local="CrearBorrarLanzador" # Nombre del archivo local
ruta_repositorio="https://github.com/sukigsx/MegaTools_gui.git" #ruta del repositorio para actualizar y clonar con git clone

# Obtener la ruta del script
descarga=$(dirname "$(readlink -f "$0")")

git clone $ruta_repositorio /tmp/comprobar >/dev/null 2>&1

diff $descarga/$archivo_local /tmp/comprobar/$archivo_local >/dev/null 2>&1


if [ $? = 0 ]
then
    #esta actualizado, solo lo comprueba
    #echo ""
    #echo -e "${verde} El script${borra_colores} $0 ${verde}esta actualizado.${borra_colores}"
    #echo ""
    var_actualizado="SI"
    chmod -R +w /tmp/comprobar
    rm -R /tmp/comprobar
else
    #hay que actualizar, comprueba y actualiza
    #echo ""
    zenity --warning --title="Megatools - ( Diseñado por SIKIGSX )" --text="Se va a proceder a la actualizacion del componente CREAR LANZADOR de forma automatica.\nSeleccionalo de nuevo" --width=650
    mv /tmp/comprobar/$descarga/$archivo_local $descarga
    chmod -R +w /tmp/comprobar
    rm -R /tmp/comprobar
    #echo ""
    #echo -e "${verde} El script se ha actualizado.${borra_colores}"
    #sleep 2
    exit
fi
}

actualizar_script

while :
do
    opcion=$(zenity --list --title="Crear lanzador - MegaTools ( Diseñado por SUKIGSX )" \
    --text="Informacion relacionada al Megatools" \
    --column "Opciones para crear el lanzador:" --column="Descripcion." \
    "Crear lanzador" "Crea el lanzador en tu escritorio" \
    "Borrar lanzador" "Borra el lanzador de tu escritorio." \
    --width=650 \
    --height=250 \
    --extra-button="Salir sin preguntar" \
    --ok-label="Aceptar" \
    --cancel-label="Atras")

    # Manejar la opción seleccionada
    case $opcion in
        "Crear lanzador")
            #recopila la ruta de donde esta el script
            ruta_script=$(dirname "$(readlink -f "$0")")
            #comprueba que exista la carpeta Escritorio
            if [ -d /home/$(whoami)/Escritorio/ ];then
                ruta_lanzador=/home/$(whoami)/Escritorio
            else
                ruta_lanzador=/home/$(whoami)/Desktop
            fi
            echo '[Desktop Entry]' >> $ruta_lanzador/MegaTools.desktop
            echo 'Comment[es_ES]=' >> $ruta_lanzador/MegaTools.desktop
            echo 'Comment=' >> $ruta_lanzador/MegaTools.desktop
            echo 'Exec=nohup bash megatools.sh' >> $ruta_lanzador/MegaTools.desktop
            echo 'GenericName[es_ES]=' >> $ruta_lanzador/MegaTools.desktop
            echo 'GenericName=' >> $ruta_lanzador/MegaTools.desktop
            echo "Icon=autocorrection" >> $ruta_lanzador/MegaTools.desktop
            echo 'MimeType=' >> $ruta_lanzador/MegaTools.desktop
            echo 'Name[es_ES]=MegaTools ( Por SUKIGSX )' >> $ruta_lanzador/MegaTools.desktop
            echo 'Name=MegaTools ( Por SUKIGSX )' >> $ruta_lanzador/crear_prompt.desktop
            echo "Path=$ruta_script" >> $ruta_lanzador/MegaTools.desktop
            echo 'StartupNotify=true' >> $ruta_lanzador/MegaTools.desktop
            echo 'Terminal=false' >> $ruta_lanzador/MegaTools.desktop
            echo 'TerminalOptions=' >> $ruta_lanzador/MegaTools.desktop
            echo 'Type=Application' >> $ruta_lanzador/MegaTools.desktop
            echo 'X-DBUS-ServiceName=' >> $ruta_lanzador/MegaTools.desktop
            echo 'X-DBUS-StartupType=none' >> $ruta_lanzador/MegaTools.desktop
            echo 'X-KDE-SubstituteUID=false' >> $ruta_lanzador/MegaTools.desktop
            echo 'X-KDE-Username=' >> $ruta_lanzador/MegaTools.desktop
            zenity --info --title="MegaTools ( Diseñado por SUKIGSX )" --text="Lanzador creado en tu escritorio." --width=300
            ;;

        "Borrar lanzador")
            #comprueba que exista la carpeta Escritorio
            if [ -d /home/$(whoami)/Escritorio/ ];then
                ruta_lanzador=/home/$(whoami)/Escritorio
            else
                ruta_lanzador=/home/$(whoami)/Desktop
            fi

            if [ -f $ruta_lanzador/MegaTools.desktop ] ;then
                zenity --question --title="MegaTools ( Diseñado por SUKIGSX )" --text="¿Seguro que quieres borrar el lanzador?" --cancel-label="No" --ok-label="Si" --width=200
                if [ $? = 0 ]; then
                    rm $ruta_lanzador/MegaTools.desktop
                    zenity --info --title="MegaTools ( Diseñado por SUKIGSX )" --text="Lanzador borrado." --width=300 --timeout=3
                else
                    zenity --info --title="MegaTools ( Diseñado por SUKIGSX )" --text="Cancelado. No se borra el lanzador." --width=300 --timeout=3
                fi
            else
                zenity --info --title="MegaTools ( Diseñado por SUKIGSX )" --text="No existe lanzador." --width=300 --timeout=3
            fi
            ;;

        "Salir sin preguntar")
            # Leer el PID del archivo para matar el script pricipal
            uno_pid=$(</tmp/ProcesoPidDeMegatools)

            # Matar el proceso de uno.sh
            kill $uno_pid
            exit
            ;;

        *)
            if [ $? -eq 0 ]; then
                zenity --error --title="MegaTools ( Diseñado por SUKIGSX )" --text="No has seleccionado ninguna opcion del menu." --width=300
            else
              exit
            fi
            ;;
    esac
done
