#!/bin/bash
ruta_ejecucion=$(dirname "$(readlink -f "$0")")

#colores
#ejemplo: echo -e "${verde} La opcion (-e) es para que pille el color.${borra_colores}"

rojo="\e[0;31m\033[1m" #rojo
verde="\e[;32m\033[1m"
azul="\e[0;34m\033[1m"
amarillo="\e[0;33m\033[1m"
rosa="\e[0;35m\033[1m"
turquesa="\e[0;36m\033[1m"
borra_colores="\033[0m\e[0m" #borra colores








#comprobamos la conexion a internet
if ping -c1 google.com &>/dev/null
then
    conexion="SI"
    #zenity --info --title="Creado por SUKIGSX" --text=" Conexion a internet OK" --timeout=2 --width=300 #--height=5
    #zenity --info --title="Creado por SUKIGSX" --text="Se va a comprobar el software necesario." --timeout=2
    #zenity --info --title="Creado por SUKIGSX" --text="$(software_necesario)"
else
    conexion="NO"
    zenity --error --title="-MegaTools-" --text=" Fallo de Conexion a internet, NO se puede continuar." --ok-label="Salir" --width=300 --height=50 --timeout=10
    exit
fi





# Menú principal
while :
do
opcion=$(zenity --list --title="Crear Prompt -MegaTools-" \
--text="Crear prompt para tu terminal de linux bash." \
--column="Menu de opciones" --column="Descripcion" \
"Crear prompt nuevo" "Diseña e instala tu prompt para la terminal bash." \
"Borrar prompt" "Borra el prompt que tengas diseñado con esta aplicacion." \
"" "" \
"Ayuda" "Su nombre lo dice, carga la ayuda de la aplicacion." \
--width=650 \
--height=300 \
--ok-label="Aceptar" \
--cancel-label="Atras")

# Verificar si se presionó Cancelar o se cerró la ventana
if [ $? -ne 0 ]; then
    exit 0
else
    # Ejecutar la opción seleccionada solo si no se ha presionado Cancelar o cerrado la ventana
    case $opcion in
        "Crear un lanzador")
            #recopila la ruta de donde esta el script
            ruta_script=$(dirname "$(readlink -f "$0")")
            #comprueba que exista la carpeta Escritorio
            if [ -d /home/$(whoami)/Escritorio/ ];then
                ruta_lanzador=/home/$(whoami)/Escritorio
            else
                ruta_lanzador=/home/$(whoami)/Desktop
            fi
            echo '[Desktop Entry]' >> $ruta_lanzador/crear_prompt.desktop
            echo 'Comment[es_ES]=' >> $ruta_lanzador/crear_prompt.desktop
            echo 'Comment=' >> $ruta_lanzador/crear_prompt.desktop
            echo 'Exec=nohup bash crear_prompt.sh' >> $ruta_lanzador/crear_prompt.desktop
            echo 'GenericName[es_ES]=' >> $ruta_lanzador/crear_prompt.desktop
            echo 'GenericName=' >> $ruta_lanzador/crear_prompt.desktop
            echo "Icon=autocorrection" >> $ruta_lanzador/crear_prompt.desktop
            echo 'MimeType=' >> $ruta_lanzador/crear_prompt.desktop
            echo 'Name[es_ES]=CrearPrompt: por SUKIGSX' >> $ruta_lanzador/crear_prompt.desktop
            echo 'Name=CrearPromptpor SUKIGSX' >> $ruta_lanzador/crear_prompt.desktop
            echo "Path=$ruta_script" >> $ruta_lanzador/crear_prompt.desktop
            echo 'StartupNotify=true' >> $ruta_lanzador/crear_prompt.desktop
            echo 'Terminal=false' >> $ruta_lanzador/crear_prompt.desktop
            echo 'TerminalOptions=' >> $ruta_lanzador/crear_prompt.desktop
            echo 'Type=Application' >> $ruta_lanzador/crear_prompt.desktop
            echo 'X-DBUS-ServiceName=' >> $ruta_lanzador/crear_prompt.desktop
            echo 'X-DBUS-StartupType=none' >> $ruta_lanzador/crear_prompt.desktop
            echo 'X-KDE-SubstituteUID=false' >> $ruta_lanzador/crear_prompt.desktop
            echo 'X-KDE-Username=' >> $ruta_lanzador/crear_prompt.desktop
            zenity --info --title="Crear Prompt -MegaTools-" --text="Lanzador creado en tu escritorio." --width=200
            ;;

        "Crear prompt nuevo")
            bash $ruta_ejecucion/crear_prompt_nuevo.PromptTerminal_gui
            ;;
        "Borrar prompt")
            if zenity --question --title="Crear Prompt -MegaTools-" --text="¿Quieres borrar el prompt que tienes actualmente?\n\n- Se borrara la entrada del .bashrc.\n- Se eliminara el fichero que guarda el prompt." --title="Confirmación de borrado" --cancel-label="No" --ok-label="Si"; then
                rm -r /home/$(whoami)/.config/crear_prompt 1> /dev/null 2> /dev/null
                sed -i "/source \/home\/$(whoami)\/.config\/crear_prompt\/prompt/d" /home/$(whoami)/.bashrc
                zenity --info --title="Crear Prompt -MegaTools-" --text="Prompt borrado = ok\nEntrada del bashrc eliminada = ok\nFichero configuracion eliminado = ok" --timeout=5

            else
                zenity --error --title="Crear Prompt -MegaTools-" --text="Se cancela el borrado del Prompt" --timeout=2
            fi
            ;;

        "Ayuda")
            zenity --text-info --title="Crear Prompt -MegaTools-" --filename="$ruta_ejecucion/ayuda.PromptTerminal_gui" --cancel-label="Ver mas grande" --ok-label="Aceptar" --width=600 --height=400
            if [ $? = 0 ]; then
                echo ""
            else
                zenity --text-info --title="Crear Prompt -MegaTools-" --filename="$ruta_ejecucion/ayuda.PromptTerminal_gui" --cancel-label="Menu principal" --ok-label="Aceptar" --width=1500 --height=1000
            fi
            ;;
        *)
            zenity --error --title="Crear Prompt -MegaTools-" --text="No has seleccionado una opcion del menu."
            ;;
    esac
fi
done
