#!/bin/bash
ruta_ejecucion=$(dirname "$(readlink -f "$0")")
ruta_escritorio=$(xdg-user-dir DESKTOP)
#colores
#ejemplo: echo -e "${verde} La opcion (-e) es para que pille el color.${borra_colores}"

rojo="\e[0;31m\033[1m" #rojo
verde="\e[;32m\033[1m"
azul="\e[0;34m\033[1m"
amarillo="\e[0;33m\033[1m"
rosa="\e[0;35m\033[1m"
turquesa="\e[0;36m\033[1m"
borra_colores="\033[0m\e[0m" #borra colores

#comprobamos la conexion a internet
if ping -c1 google.com &>/dev/null
then
    conexion="SI"
    #zenity --info --title="Creado por SUKIGSX" --text=" Conexion a internet OK" --timeout=2 --width=300 #--height=5
    #zenity --info --title="Creado por SUKIGSX" --text="Se va a comprobar el software necesario." --timeout=2
    #zenity --info --title="Creado por SUKIGSX" --text="$(software_necesario)"
else
    conexion="NO"
    zenity --error --title="-MegaTools-" --text=" Fallo de Conexion a internet, NO se puede continuar." --ok-label="Salir" --width=300 --height=50 --timeout=10
    exit
fi





# Menú principal
while :
do
opcion=$(zenity --list --title="Crear Prompt -MegaTools-" \
--text="Crear prompt para tu terminal de linux bash." \
--column="Menu de opciones" --column="Descripcion" \
"Crear prompt nuevo" "Diseña e instala tu prompt para la terminal bash." \
"Borrar prompt" "Borra el prompt que tengas diseñado con esta aplicacion." \
"Exportar el prompt" "Guarda tu prompt en un fichero de texto en tu escritorio." \
"" "" \
"Ayuda" "Su nombre lo dice, carga la ayuda de la aplicacion." \
--width=650 \
--height=300 \
--ok-label="Aceptar" \
--cancel-label="Atras")

# Verificar si se presionó Cancelar o se cerró la ventana
if [ $? -ne 0 ]; then
    exit 0
else
    # Ejecutar la opción seleccionada solo si no se ha presionado Cancelar o cerrado la ventana
    case $opcion in

        "Crear prompt nuevo")
            bash $ruta_ejecucion/crear_prompt_nuevo.PromptTerminal_gui
            ;;
        "Borrar prompt")
            if zenity --question --title="Crear Prompt -MegaTools-" --text="¿Quieres borrar el prompt que tienes actualmente?\n\n- Se borrara la entrada del .bashrc.\n- Se eliminara el fichero que guarda el prompt." --title="Confirmación de borrado" --cancel-label="No" --ok-label="Si"; then
                rm -r /home/$(whoami)/.config/crear_prompt 1> /dev/null 2> /dev/null
                sed -i "/source \/home\/$(whoami)\/.config\/crear_prompt\/prompt/d" /home/$(whoami)/.bashrc
                zenity --info --title="Crear Prompt -MegaTools-" --text="Prompt borrado = ok\nEntrada del bashrc eliminada = ok\nFichero configuracion eliminado = ok" --timeout=5

            else
                zenity --error --title="Crear Prompt -MegaTools-" --text="Se cancela el borrado del Prompt" --timeout=2
            fi
            ;;

        "Exportar el prompt")
            if [ -f /home/$(whoami)/.config/crear_prompt/prompt ]; then
                cp /home/$(whoami)/.config/crear_prompt/prompt $ruta_escritorio/PromptPersonalizado.txt
                zenity --info --title="Crear Prompt -MegaTools-" --text="Se ha guardado un fichero de texto en tu escritorio con tu prompt personalizado\n\nNombre: PromptPersonalizado.txt\nRuta: $ruta_escritorio" --ok-label="Aceptar" --width=200 --height=100 --timeout=10
            else
                zenity --error --title="Crear Prompt -MegaTools-" --text="No tienes un prompt personalizado creado.\n\nCrea uno primero." --ok-label="Aceptar" --width=200 --height=100 --timeout=10
            fi
            ;;

        "Ayuda")
            zenity --text-info --title="Crear Prompt -MegaTools-" --filename="$ruta_ejecucion/ayuda.PromptTerminal_gui" --cancel-label="Ver mas grande" --ok-label="Aceptar" --width=600 --height=400
            if [ $? = 0 ]; then
                echo ""
            else
                zenity --text-info --title="Crear Prompt -MegaTools-" --filename="$ruta_ejecucion/ayuda.PromptTerminal_gui" --cancel-label="Menu principal" --ok-label="Aceptar" --width=1500 --height=1000
            fi
            ;;
        *)
            zenity --error --title="Crear Prompt -MegaTools-" --text="No has seleccionado una opcion del menu."
            ;;
    esac
fi
done
