#!/bin/bash
ruta_ejecucion=$(dirname "$(readlink -f "$0")")

CrearInstalarSoftware(){
#pregunta si quiero guardar la instalacion
if zenity --question --title="Instalacion de software - MegaTools -" --text="¿Quieres guardar un script de instalacion del software seleccionado?\n\nSe guardara en tu escritorio." --cancel-label="No" --ok-label="Si"
then
    #entra si la respuesta es si
    if [ -d /home/$(whoami)/Escritorio ]
    then
        #rm /tmp/software /home/$(whoami)/Escritorio/InstalarSosftware.sh 2>/dev/null
        cp /tmp/software /home/$(whoami)/Escritorio/InstalarSosftware.sh
    else
        #rm /tmp/software /home/$(whoami)/Desktop/InstalarSoftware.sh 2>/dev/null
        cp /tmp/software /home/$(whoami)/Desktop/InstalarSoftware.sh
    fi
else
    echo ""
fi
}


password(){
# Inicializar el contador de intentos
    attempts=0

    # Bucle para solicitar la contraseña hasta tres intentos
    while [ $attempts -lt 3 ]; do
        # Solicitar la contraseña del usuario actual utilizando Zenity
        PASSWORD=$(zenity --entry --hide-text --text="Ingrese tu contraseña" --title="Contraseña de usuario. - MegaTools -" --width=450 --height=100)

        # Verificar si se ha cancelado la entrada de la contraseña
        if [ $? -ne 0 ]; then
            # Salir del script si se ha cancelado
            rm /tmp/software 2>/dev/null
            rm /tmp/ComprobarSoftware 2>/dev/null
            rm /tmp/comprobacion 2>/dev/null
            exit
        fi

        # Verificar la contraseña utilizando el comando sudo
        echo "$PASSWORD" | sudo -S ls /root >/dev/null 2>&1

        # Verificar el código de salida del comando sudo
        if [ $? -eq 0 ]; then
            # Contraseña correcta
            zenity --info --title="Contraseña de usuario. - MegaTools -" --text="La contraseña es correcta." --width=250 --height=100 --timeout 3
            break
        else
            # Contraseña incorrecta
            let "attempts+=1"
            if [ $attempts -lt 3 ]; then
                zenity --error --title="Contraseña de usuario. - MegaTools -" --text="La contraseña es incorrecta. Inténtelo de nuevo." --width=250 --height=100 --timeout 3
            else
                zenity --error --title="Contraseña de usuario. - MegaTools -" --text="Se han superado los tres intentos. Se regresa al menu principal." --width=250 --height=100 --timeout 7
                rm /tmp/software 2>/dev/null
                exit
            fi
        fi
    done
}

#Elimina el fichero /tmp/software donde mete la informacion de los paquetes a instalar.
rm /tmp/software 2>/dev/null
rm /tmp/ComprobarSoftware 2>/dev/null
rm /tmp/comprobacion 2>/dev/null

#crea el fichero de instalacion de software
echo 'echo -e "\n- ACTUALIZANDO REPOSITORIOS.- \n"' >> /tmp/software
echo 'sudo apt update' >> /tmp/software
echo 'echo -e "\n- ACTUALIZACION DE REPOSITORIOS FINALIZADA. -"' >> /tmp/software
echo 'echo ""' >> /tmp/software
echo 'echo "- COMENZANDO LA INSTALACION DE SOFTWARE -"' >> /tmp/software
echo 'echo "- Se paciente.. El tiempo depende de tu conexion. -"; sleep 2' >> /tmp/software

#crea el fichero para comprobar la instalacion
echo 'for programa in $(cat /tmp/ComprobarSoftware); do' >> /tmp/comprobacion
echo '    if which "$programa" &>/dev/null; then' >> /tmp/comprobacion
echo '        echo "$programa [ OK ]."' >> /tmp/comprobacion
echo '    else' >> /tmp/comprobacion
echo '        echo "$programa [ NO INSTALADO ]."' >> /tmp/comprobacion
echo '    fi' >> /tmp/comprobacion
echo 'done' >> /tmp/comprobacion
echo "sudo rm /usr/bin/Tienda_AppImage.AppImage 2>/dev/null" >> /tmp/comprobacion
echo "sudo rm /usr/bin/net-tools 2>/dev/null" >> /tmp/comprobacion

while :
do

    opcion=$(zenity --list --title="Instalacion de Software. - MegaTools -" \
    --text="\nSelecciona una categoria de software y vete marcando el que mas te guste o necesites.\n" \
    --column "Categorias principales:" --column="Descripcion." \
    "NAVEGADORES" "Los principales navegadores para internet." \
    "AUDIO - VIDEO" "Software relacionado el el Audio y el Video." \
    "ENTORNOS GRAFICOS LINUX   " "Los principales entornos graficos para linux basados en debian." \
    "UTILIDADES" "Cantidad de utilidades" \
    "OFIMATICA" "Software dedicado a la ofimatica" \
    "SERVIDORES" "Servidores para tu sistema, (ssh, ftp, smb, etc)" \
    "GESTOR DE PAQUETES" "Software para el control de paquetes. (snap apt etc)." \
    "PARA TU TERMINAL" "Software pensado para la terminal linux." \
    "DISCOS" "Software de control de discos duros y unidades en general." \
    "JUEGOS" "Pues ya lo dice todo, juegos." \
    "SEGURIDAD" "Software destinado a la seguridad de tu equipo." \
    "MENSAJERIA" "Software de mensajeria en red." \
    "" "" \
    "PAQUETES INDEPENDIENTES" "Descarga e instala paquetes deb manualmente." \
    --width=650 \
    --height=650 \
    --ok-label="Aceptar" \
    --cancel-label="Atras" \
    --extra-button="Ayuda instalacion de software" \
    --extra-button="Ver software para instalar")

    # Manejar la opción seleccionada
    case $opcion in

        "NAVEGADORES")
            bash $ruta_ejecucion/Navegadores
            ;;

        "AUDIO - VIDEO")
            bash $ruta_ejecucion/AudioVideo
            ;;

        "ENTORNOS GRAFICOS LINUX   ")
            bash $ruta_ejecucion/EntornosGraficosLinux
            ;;

        "UTILIDADES")
            bash $ruta_ejecucion/Utilidades
            ;;

        "OFIMATICA")
            bash $ruta_ejecucion/Ofimatica
            ;;

        "SERVIDORES")
            bash $ruta_ejecucion/Servidores
            ;;

        "GESTOR DE PAQUETES")
            bash $ruta_ejecucion/GestorDePaquetes
            ;;

        "PARA TU TERMINAL")
            bash $ruta_ejecucion/Terminal
            ;;

        "DISCOS")
            bash $ruta_ejecucion/Discos
            ;;

        "JUEGOS")
            bash $ruta_ejecucion/Juegos
            ;;

        "SEGURIDAD")
            bash $ruta_ejecucion/Seguridad
            ;;

        "MENSAJERIA")
            bash $ruta_ejecucion/Mensajeria
            ;;

        "PAQUETES INDEPENDIENTES")
            bash $ruta_ejecucion/PaquetesIndependientesNavegador
            ;;

        "Ayuda instalacion de software")
            zenity --text-info --title="Ayuda - MegaTools -" --filename=$ruta_ejecucion/AyudaInstalacionSoftware --font="DejaVu Sans Mono" --width=650 --height=650
            ;;

        "Ver software para instalar")
            #muestra el software seleccionado
            if grep -q '^#' /tmp/software 2>/dev/null; then #comprueba si hay algun software para instalar verificando la #
                #elimina lineas duplicadas del fichero de instalacion
                awk '!seen[$0]++' /tmp/software > /tmp/software_sin_duplicados
                mv /tmp/software_sin_duplicados /tmp/software

                awk '!seen[$0]++' /tmp/ComprobarSoftware > /tmp/ComprobarSoftware_duplicados
                mv /tmp/ComprobarSoftware_duplicados /tmp/ComprobarSoftware

                (echo -e "\nEste es tu software para instalar\n"; grep '^#' /tmp/software | sed 's/^#/- /') | zenity --text-info --width=600 --height=400 --title="Software para instalar. - MegaTools" --auto-scroll --font="DejaVu Sans Mono" --cancel-label="Cancelar, Empezar de nuevo" --ok-label="Instalar"

                #comprueba si le damos a cancelar si es asi, sale del script al anterior
                if [ $? = 1 ]; then
                    #Elimina el fichero /tmp/software donde mete la informacion de los paquetes a instalar.
                    rm /tmp/software 2>/dev/null
                    rm /tmp/ComprobarSoftware 2>/dev/null
                    rm /tmp/comprobacion 2>/dev/null
                    exit
                fi
                #le hemos dado a instalar y pregunta la password
                password

                #ejecuta el fichero de instalacion
                (bash /tmp/software 2>/dev/null; echo -e "\n- TERMINADO EL PROCESO DE INSTALACION DE SOFTWARE -") | zenity --text-info --width=600 --height=400 --title="Instalando software seleccionado. - MegaTools" --auto-scroll --font="DejaVu Sans Mono"

                #verifica el software que se ha instalado
                (echo -e "\n - VERIFICACION DEL SOFTWARE INSTALADO -\n"; bash /tmp/comprobacion 2>/dev/null; echo -e "\n- TERMINADO EL PROCESO DE VERIFICACION -") | zenity --text-info --width=600 --height=400 --title="Verificacion de software. - MegaTools" --auto-scroll

                CrearInstalarSoftware
                exit

            else
                zenity --error --title="Instalacion del software seleccionado. - MegaTools -" --text="No hay seleccionado ningun software para instalar." --width=400
            fi

            ;;

        *)
            if [ $? -eq 0 ]; then
                zenity --error --title="Instalacion del software seleccionado.- MegaTools -" --text="No has seleccionado ninguna categoria del menu." --width=400
            else
                #Elimina el fichero /tmp/software donde mete la informacion de los paquetes a instalar.
                rm /tmp/software 2>/dev/null
                rm /tmp/ComprobarSoftware 2>/dev/null
                rm /tmp/comprobacion 2>/dev/null
                exit 0
            fi
            ;;
    esac
done
#Elimina el fichero /tmp/software donde mete la informacion de los paquetes a instalar.

rm /tmp/software 2>/dev/null
rm /tmp/ComprobarSoftware 2>/dev/null
rm /tmp/comprobacion 2>/dev/null
