#!/bin/bash
ruta_descargas=$(xdg-user-dir DOWNLOAD)
ruta_ejecucion=$(dirname "$(readlink -f "$0")")

comprobar_navegador(){
if which $navegador
then
    navegador_seleccionado=$navegador
else
    zenity --error --title="Instalacion de Paquetes Independientes - Megatools -" --text="No dispones del navegador $navegador.\nPuedes instalarlo del menu Navegadores." --width=400
    exit
fi
}

while :
do
    # selecciona el navegador preferido
    navegador=$(zenity --list --title="Instalacion de Paquetes Independientes. - MegaTools" \
    --text="\n Forma de instalacion de los paquetes independientes.\n \
    \n 1- Selecciona un navegador. \
    \n 2- Selecciona el software que te interese. \
    \n 3- Se abrira el navegador que hayas seleccionado anteriormente, en la pagina para descargar el paquete deb.\
    \n 4- Descargalo en la carpeta DESCARGAS (Si no esta en esa ruta, NO lo encontrar para su instalacion).\
    \n 5- Dale al boton Instalar y empezara el proceso de instalacion de todos los paquetes deb descargados. \
    \n 6- Cuando termine se borraran todos los paquetes deb de la carpeta descargas.\
    \n" \
    --column="Selecciona tu navegador" --column="Descripcion." \
    --width=300 --height=200 \
    --cancel-label="Atras" \
    --ok-label="Siguiente" \
    --width=950 \
    --height=650 \
    "google-chrome-stable" "Navegador para descargar tu paquete deb." \
    "chromium-browser" "Navegador para descargar tu paquete deb." \
    "firefox" "Navegador para descargar tu paquete deb." \
    "opera" "Navegador para descargar tu paquete deb." \
    "brave" "Navegador para descargar tu paquete deb." \
    "vivaldi-stable" "Navegador para descargar tu paquete deb." \
    )

    case $navegador in
        "firefox")
            comprobar_navegador
            break
            ;;

        "google-chrome-stable")
            comprobar_navegador
            break
            ;;

        "chromium-browser")
            comprobar_navegador
            break
            ;;

        "opera")
            comprobar_navegador
            break
            ;;

        "brave")
            comprobar_navegador
            break
            ;;

        "vivaldi-stable")
            comprobar_navegador
            break
            ;;

        *)
            if [ $? -eq 0 ]; then
                zenity --error --title="Instalacion de Paquetes Independientes - Megatools -" --text="No has seleccionado ningun navegador del menu.\nSe necesita uno para poder descargar el paquete deb." --width=400
            else
                exit 0
            fi
            ;;
    esac
done


while :
do
    # Mostrar el menú de selección utilizando Zenity
    selection=$(zenity --list --title="Instalacion de Paquetes Independientes. - MegaTools" \
    --text="\n Forma de instalacion de los paquetes independientes de paquetes independientes.\n \
    \n - Selecciona el software que te interese. Y le das al boton Descargar. \
    \n - Se abrira el navegador que hayas seleccionado anteriormente, en la pagina para descargar el paquete deb.\
    \n - Descargalo en la carpeta DESCARGAS (Si no esta en esa ruta, NO lo encontrar para su instalacion).\
    \n - Dale al boton Instalar y empezara el proceso de instalacion de todos los paquetes deb descargados en la carpeta DESCARGAS. \
    \n - Cuando termine se borraran todos los paquetes deb de la carpeta descargas.\
    \n" \
    --column="Paquetes independientes" --column="Descripcion." \
    --width=300 --height=200 \
    --cancel-label="Atras" \
    --ok-label="Descargar" \
    --extra-button="Instalar" \
    --width=950 \
    --height=650 \
    "GitHub Desktop" "Control de versiones de GitHup de tus proyectos en forma grafica." \
    "VirtualBox" "Sostware gratuito para crear maquinas virtuales." \
    )

    case $selection in
        "GitHub Desktop")
            $navegador https://github.com/shiftkey/desktop/releases &>/dev/null
            ;;

        "VirtualBox")
            $navegador https://www.virtualbox.org/wiki/Linux_Downloads &>/dev/null
            ;;

        "Instalar")
            # Verificar si existen archivos *.deb en la carpeta Descargas
            if ls "$ruta_descargas"/*.deb 1> /dev/null 2>&1; then
                echo "Existen archivos *.deb en la carpeta Descargas."
            else
                echo "No existen archivos *.deb en la carpeta Descargas."
            fi
            ;;

        *)
            if [ $? = 1 ]; then
                break
            else
                zenity --error --title="Instalacion de Paquetes Independientes - MegaTools -" --text=" No has seleccionado ningun Paquete Independiente, para su instalacion." --width=400
            fi
            ;;
    esac
done
