#!/bin/bash

conexion(){
if ping -c1 google.com &>/dev/null
then
    var_conexion="SI"
else
    var_conexion="NO"
    var_actualizado="No hay conexion a internet"
fi
}

while :
do
    # Mostrar el menú de selección utilizando Zenity
    selection=$(zenity --list --title="Instalar Utilidades. - MegaTools" \
    --text="\nSoftware disponible de utilidades para entornos linux.\n" \
    --checklist --column="Marca una o varias casillas para instalar" --column="Utilidades" --column="Descripcion." \
    --width=300 --height=200 \
    --cancel-label="Atras" \
    --ok-label="Aceptar" \
    --width=950 \
    --height=650 \
    FALSE "Grub-customizer" "Modifica el gestor de arranque." \
    FALSE "Cairo-Dock" "Crear paneles y lanzadores, muy personalizados." \
    FALSE "Latte-dock" "Crear lanzadores, muy personalizados." \
    FALSE "Tellico" "Crea tu base de datos de cd dvd libros etc." \
    FALSE "KDE Connect" "Sincroniza tu movil con el pc." \
    FALSE "Usuarios y Grupos" "Gestiona Usuarios y Grupos de modo grafico." \
    FALSE "Gnome-online-accouns   " "Para poder sincronizar cuentas de google (drive)." \
    FALSE "Kio gdrive" "Para poder sincronizar cuentas de google (drive) solo entornos KDE Plasma." \
    FALSE "Ocamlfuse" "Otro para poder sincronizar cuentas de google (drive)." \
    FALSE "Nemo" "Explorador de ficheos." \
    FALSE "Systemback" "Utilidades para gestionar el sistema." \
    FALSE "Deja-dup" "Copoa de seguridad de tus ficheros o sistema." \
    FALSE "Transmision" "Gestor de descargas torrent." \
    FALSE "Software-propietario" "Gestionar ppa y drives en modo grafico" \
    FALSE "Joplin" "Software multiplataforma para tomar notas." \
    FALSE "Keepass2" "Gestor de contraseñas." \
    )

    # Verificar si se presionó "Atras" en el diálogo de Zenity
    if [ $? -eq 1 ]; then
        exit 0
    fi

    # Verificar si no se seleccionó ninguna opción
    if [ -z "$selection" ]; then
        zenity --error --title="Instalacion de Utilidades - MegaTools -" --text="No has seleccionado ninguna Utilidad." --width=300
    else
        echo ""
    fi


    # Verificar las opciones seleccionadas y ejecutar los comandos correspondientes
    IFS="|" read -ra selected_options <<< "$selection"  # Establecer el separador como "|"
    for option in "${selected_options[@]}"; do
        case $option in
            "Grub-customizer")
                #codigo para la instalacion se mete a /tmp/software
                echo "#vlc" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y vlc" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "vlc" >> /tmp/ComprobarSoftware
                ;;

            "Cairo-Dock")
                #codigo para la instalacion se mete a /tmp/software
                echo "#spotify" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y snapd; sudo snap install spotify" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "spotify" >> /tmp/ComprobarSoftware
                ;;

            "Latte-dock")
                #codigo para la instalacion se mete a /tmp/software
                echo "#digikam" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y digikam" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "digikam" >> /tmp/ComprobarSoftware
                ;;

            "Tellico")
                #codigo para la instalacion se mete a /tmp/software
                echo "#simple-scan" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y simple-scan" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "simple-scan" >> /tmp/ComprobarSoftware
                ;;

            "KDE Connect")
                #codigo para la instalacion se mete a /tmp/software
                echo "#handbrake" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y handbrake" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "handbrake" >> /tmp/ComprobarSoftware
                ;;

            "Usuarios y Grupos")
                #codigo para la instalacion se mete a /tmp/software
                echo "#shotwell" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y shotwell" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "shotwell" >> /tmp/ComprobarSoftware
                ;;

            "Gnome-online-accouns   ")
                #codigo para la instalacion se mete a /tmp/software
                echo "#skanlite" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y skanlite" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "skanlite" >> /tmp/ComprobarSoftware
                ;;

            "Kio gdrive")
                #codigo para la instalacion se mete a /tmp/software
                echo "#krita" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y krita" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "krita" >> /tmp/ComprobarSoftware
                ;;

            "Ocamlfuse")
                #codigo para la instalacion se mete a /tmp/software
                echo "#krita" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y krita" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "krita" >> /tmp/ComprobarSoftware
                ;;

            "Nemo")
                #codigo para la instalacion se mete a /tmp/software
                echo "#krita" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y krita" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "krita" >> /tmp/ComprobarSoftware
                ;;

            "Systemback")
                #codigo para la instalacion se mete a /tmp/software
                echo "#krita" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y krita" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "krita" >> /tmp/ComprobarSoftware
                ;;

            "Deja-dup")
                #codigo para la instalacion se mete a /tmp/software
                echo "#krita" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y krita" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "krita" >> /tmp/ComprobarSoftware
                ;;

            "Transmision")
                #codigo para la instalacion se mete a /tmp/software
                echo "#krita" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y krita" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "krita" >> /tmp/ComprobarSoftware
                ;;

            "Software-propietario")
                #codigo para la instalacion se mete a /tmp/software
                echo "#krita" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y krita" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "krita" >> /tmp/ComprobarSoftware
                ;;

            "Joplin")
                #codigo para la instalacion se mete a /tmp/software
                echo "#krita" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y krita" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "krita" >> /tmp/ComprobarSoftware
                ;;

            "Keepass2")
                #codigo para la instalacion se mete a /tmp/software
                echo "#vlc" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y vlc" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "vlc" >> /tmp/ComprobarSoftware
                ;;


            *)
            #if [ $? -eq 0 ]; then
            #    zenity --error --title="MegaTools ( Diseñado por SUKIGSX )" --text="No has seleccionado ninguna opcion del menu." --width=300
            #else
            #    zenity --question --title="MegaTools ( Diseñado por SUKIGSX )" --text="¿ Estás seguro de que deseas salir ?" --cancel-label="No" --ok-label="Si" --width=300
            #    if [ $? -eq 0 ]; then
            #        exit 0
            #    fi
            #fi
            echo "he entrado en el *"; read p
            ;;
        esac
    done
    exit #sale cuando termiona el for con lo seleccionado.
done
