#!/bin/bash

conexion(){
if ping -c1 google.com &>/dev/null
then
    var_conexion="SI"
else
    var_conexion="NO"
    var_actualizado="No hay conexion a internet"
fi
}

if [ $(which ifconfig) ]; then
    echo ""
else
    zenity --error --title="Informacion de dispositivos de red. - MegaTools -" --text="No dispones del paquete net-tools en tu sistema.\n\nPuedes instalarlo de estas formas:\n - Con MegaTools en la secion Instalacion de software/Para tu terminal\n- Con una terminal, comando = sudo apt install net-tools."
    exit
fi


while :
do
# Mostrar la salida en una ventana con Zenity
opcion=$(zenity --text-info --filename=/tmp/InfoDispositivosDeRed --title="Informacion de dispositivos de red. - MegaTools -" --ok-label="Atras" --cancel-label="Salir sin preguntar" --extra-button="Mas detalles" --extra-button="Menos detalles" --font="DejaVu Sans Mono" --width=800 --height=450)

    case $opcion in

        "Mas detalles")
            #Nombre del archivo donde se guardará la salida de ethtool
            output_file="/tmp/InfoDispositivosDeRed"

            #Limpiar el archivo de salida si ya existe
            > "$output_file"

            #Obtener una lista de todas las interfaces de red
            interfaces=$(ls /sys/class/net/)

            #Recorrer cada interfaz y ejecutar ethtool sobre ellas
            for interface in $interfaces; do
                echo "Informacion de la Tarjeta de red : $interface" >> "$output_file"
                ethtool "$interface" >> "$output_file" 2>/dev/null
                echo "" >> "$output_file"
                echo "Fin de la informacion de la tarjeta de red $interface" >> "$output_file"
                echo "" >> "$output_file"
            done
            ;;

        "Menos detalles")
            echo -e "Comando: ifconfig -s\n" > /tmp/InfoDispositivosDeRed; ifconfig -s >> /tmp/InfoDispositivosDeRed; echo -e "\nInformacion de dispositivos de red finalizado." >> /tmp/InfoDispositivosDeRed
            ;;

        *)
            if [ $? = "1" ]; then
                # Leer el PID del archivo para matar el script pricipal
                uno_pid=$(</tmp/ProcesoPidDeMegatools)

                # Matar el proceso de uno.sh
                kill $uno_pid
                rm /tmp/ProcesoPidDeMegatools
                rm /tmp/InfoDispositivosDeRed
                exit
            else
                rm /tmp/ProcesoPidDeMegatools
                rm /tmp/InfoDispositivosDeRed
                exit
            fi
        ;;
    esac
done
