#!/bin/bash

#Elimina el fichero /tmp/software donde mete la informacion de los paquetes a instalar.
rm /tmp/software 2>/dev/null

echo 'echo -e "\nActualizando repositorios.\n"' >> /tmp/software
echo 'sudo apt update' >> /tmp/software
echo 'echo -e "\nActualizacion de repositorios FINALIZADA."' >> /tmp/software

while :
do
    opcion=$(zenity --list --title="MegaTools ( Diseñado por SUKIGSX )" \
    --text="\nSelecciona una categoria de software y vete marcando el que mas te guste o necesites.\n" \
    --column "Categorias principales:" --column="Descripcion." \
    "NAVEGADORES" "Los principales navegadores para internet." \
    "AUDIO - VIDEO" "Software relacionado el el Audio y el Video." \
    "ENTORNOS GRAFICOS LINUX" "Los principales entornos graficos para linux basados en debian." \
    "UTILIDADES" "Cantidad de utilidades" \
    "OFIMATICA" "Software dedicado a la ofimatica" \
    "SERVIDORES" "Servidores para tu sistema, (ssh, ftp, smb, etc)" \
    "GESTOR DE PAQUETES" "Software para el control de paquetes. (snap apt etc)." \
    "PARA TU TERMINAL" "Software pensado para la terminal linux." \
    "DISCOS" "Software de control de discos duros y unidades en general." \
    "JUEGOS" "Pues ya lo dice todo, juegos." \
    "SEGURIDAD" "Software destinado a la seguridad de tu equipo." \
    "MENSAJERIA" "Software de mensajeria en red." \
    --width=650 \
    --height=650 \
    --ok-label="Aceptar" \
    --cancel-label="Atras" \
    --extra-button="Ver software para instalar")

    # Manejar la opción seleccionada
    case $opcion in

        "NAVEGADORES")
            bash MenuPrincipal/InstalacionDeSosfware/Navegadores
            ;;

        "AUDIO - VIDEO")
            ;;

        "ENTORNOS GRAFICOS LINUX")
            ;;

        "UTILIDADES")
            ;;

        "OFIMATICA")
            ;;

        "SERVIDORES")
            ;;

        "GESTOR DE PAQUETES")
            ;;

        "PARA TU TERMINAL")
            ;;

        "DISCOS")
            ;;

        "JUEGOS")
            ;;

        "SEGURIDAD")
            ;;

        "MENSAJERIA")
            ;;

        "Ver software para instalar")
            #muestra el software seleccionado
            grep '^#' /tmp/software | zenity --text-info --width=600 --height=400 --title="Software para instalar. - MegaTools" --auto-scroll --font="DejaVu Sans Mono"



            #empieza la instalacion
            #actualiza repositorios

            #bash /tmp/software | zenity --text-info --width=600 --height=400 --title="Instalacion del software seleccionado. - MegaTools" --auto-scroll
            ;;

        *)
            if [ $? -eq 0 ]; then
                zenity --error --title="Instalacion del software seleccionado.- MegaTools -" --text="No has seleccionado ninguna categoria del menu." --width=300
            else
                #Elimina el fichero /tmp/software donde mete la informacion de los paquetes a instalar.
                rm /tmp/software 2>/dev/null
                exit 0
            fi
            ;;
    esac
done
#Elimina el fichero /tmp/software donde mete la informacion de los paquetes a instalar.
rm /tmp/software 2>/dev/null
