#!/bin/bash

actualizar_script(){
archivo_local="InfoDeDiscos" # Nombre del archivo local
ruta_repositorio="https://github.com/sukigsx/MegaTools_gui.git" #ruta del repositorio para actualizar y clonar con git clone

# Obtener la ruta del script
descarga=$(dirname "$(readlink -f "$0")")
#descarga="/home/$(whoami)/scripts"
git clone $ruta_repositorio /tmp/comprobar >/dev/null 2>&1

diff $descarga/$archivo_local /tmp/comprobar/$archivo_local >/dev/null 2>&1


if [ $? = 0 ]
then
    #esta actualizado, solo lo comprueba
    #echo ""
    #echo -e "${verde} El script${borra_colores} $0 ${verde}esta actualizado.${borra_colores}"
    #echo ""
    var_actualizado="SI"
    chmod -R +w /tmp/comprobar
    rm -R /tmp/comprobar
else
    #hay que actualizar, comprueba y actualiza
    #echo ""
    zenity --warning --title="Megatools - ( Diseñado por SIKIGSX )" --text="Se va a proceder a la actualizacion del componente INFORMACION DE DISCOS de forma automatica.\nSeleccionalo de nuevo" --width=650
    mv /tmp/comprobar/$archivo_local $descarga
    chmod -R +w /tmp/comprobar
    rm -R /tmp/comprobar
    #echo ""
    #echo -e "${verde} El script se ha actualizado.${borra_colores}"
    #sleep 2
    exit
fi
}

actualizar_script

# Ejecutar el comando df -h y guardar la salida en una variable
echo -e "Comando: df -h\n" > /tmp/discos; df -h >> /tmp/discos; echo -e "\nFinalizada la informacion.\n" >> /tmp/discos

while :
do
# Mostrar la salida en una ventana con Zenity
opcion=$(zenity --text-info --filename=/tmp/discos --title="Informacion de discos - MegaTools" --ok-label="Atras" --cancel-label="Salir sin preguntar" --extra-button="Mas detalles" --extra-button="Menos detalles" --font="DejaVu Sans Mono" --width=800 --height=450)

    case $opcion in

        "Mas detalles")
            echo -e "Comando: lsblk -o\n" > /tmp/discos
            lsblk -o NAME,SIZE,TYPE,FSTYPE,MOUNTPOINT | sed '1s/NAME/NOMBRE/; 1s/SIZE/TAMAÑO/; 1s/TYPE/TIPO/; 1s/FSTYPE/FORMATO/; 1s/MOUNTPOINT/PUNTO_DE_MONTAJE/' | column -t -c 20 >> /tmp/discos
            ;;

        "Menos detalles")
            echo -e "Comando: df -h\n" > /tmp/discos; df -h >> /tmp/discos; echo -e "\n Finalizada la informacion.\n" >> /tmp/discos
            ;;

        *)
            if [ $? = "1" ]; then
                # Leer el PID del archivo para matar el script pricipal
                uno_pid=$(</tmp/ProcesoPidDeMegatools)

                # Matar el proceso de uno.sh
                kill $uno_pid
                rm /tmp/ProcesoPidDeMegatools
                rm /tmp/discos
                exit
            else
                rm /tmp/ProcesoPidDeMegatools
                rm /tmp/discos
                exit
            fi
        ;;
    esac
done
